name=PEL
version=0.1.0
author=PEL Team
maintainer=PEL <info@pel.dev>
sentence=PEL educational wrapper for Arduino
paragraph=Simple, readable wrapper for Arduino education and prototyping.
category=Other
url=https://github.com/initify140/PEL
architectures=*
